import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueDevTools from 'vite-plugin-vue-devtools'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    vueDevTools(),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    },
  },
  build: {
    // Build straight into the directory Tauri bundles as a resource (and serves from
    // in dev). The built bundle used to be committed and hand-copied, which meant two
    // copies of the panel and a repo that grew a new set of hash-named assets on every
    // build. It is now generated by tauri's beforeBuild/beforeDev command instead.
    outDir: '../src-tauri/idleview-control',
    emptyOutDir: true
  },
  server: {
    proxy: {
      '/api': {
        target: 'http://localhost:8737',
        changeOrigin: true,
      }
    }
  },
  test: {
    environment: 'jsdom'
  }
})
